### ISSUE TITLE
Server Docker Compose example fails

### ISSUE THREAD

**Issue by tedspare** [getzep/graphiti#454]
The example Docker Compose in [graph-service](https://github.com/getzep/graphiti/tree/main/server#graph-service) seems to have a few issues:

1. Neo4j <5.26 does not support setting labels dynamically:

```txt
neo4j.exceptions.CypherSyntaxError: {code: Neo.ClientError.Statement.SyntaxError} {message: Setting labels or properties dynamically is not supported. (line 3, column 21 (offset: 64))
```

2. The `latest` Docker build (as of the time of this writing) appears broken: #439
3. The `graph-1` service does not wait for a Neo4j instance to be running e.g. via healthcheck:

```txt
neo4j-1  | Changed password for user 'neo4j'. IMPORTANT: this change will only take effect if performed before the database is started for the first time.
graph-1  | INFO:     Started server process [7]
graph-1  | INFO:     Waiting for application startup.
graph-1  | Transaction failed and will be retried in 1.199746033919537s (Couldn't connect to neo4j:7687 (resolved to ('172.20.0.3:7687',)):
graph-1  | Failed to establish connection to ResolvedIPv4Address(('172.20.0.3', 7687)) (reason [Errno 111] Connect call failed ('172.20.0.3', 7687)))
```

An example `server/docker-compose.yml` working on my end:

```yml
services:
  neo4j:
    image: neo4j:5.26.0

    ports:
      - "7474:7474" # HTTP
      - "${NEO4J_PORT}:${NEO4J_PORT}" # Bolt
    volumes:
      - neo4j_data:/data
    environment:
      - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASSWORD}
    healthcheck:
      test: wget "http://localhost:${NEO4J_PORT}" || exit 1
      interval: 1s
      timeout: 10s
      retries: 20
      start_period: 3s
  graph:
    image: zepai/graphiti:latest # once working
    ports:
      - "8000:8000"
    depends_on:
      neo4j:
        condition: service_healthy
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - NEO4J_URI=bolt://neo4j:${NEO4J_PORT}
      - NEO4J_USER=${NEO4J_USER}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}

volumes:
  neo4j_data:
```
